server:
  port: 8090
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  #      additional-paths: src/main/java #重启目录
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gcmp?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
#  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
gcmp:
  taskLogLines: 100
  pypiSource: https://pypi.tuna.tsinghua.edu.cn/simple
  k8sConfigFilePath: "src/main/resources/config"
  ftpType: ftp
  adminName: admin
  server-properties:
    - { hostName: node1, hostIp: 192.168.0.107, username: root, password: 123456, gpus: 1, gpuSeries: GTX1080 }

  docker-client-port: 2375
  docker-file-root: /home/gcmp/dockerfiles
  data-root: /home/gcmp/data
  temp-file-root: /home/gcmp/temp

ftp-pool:
  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  blockWhenExhausted: true
  #最大空闲等待时间(毫秒)，建议设置稍微长点，如90分钟
  #  maxWaitMillis: 5400000
  #最大连接数
  maxTotal: 5
  #最大空闲连接数
  maxIdle: 5
  #最小空闲连接数
  minIdle: 2
  #申请连接时 检测是否有效
  testOnBorrow: true
  #返回连接时 检测是否有效
  testOnReturn: false
  #创建连接时 检测是否有效
  testOnCreate: false
  #空闲时检测连接是否有效
  testWhileIdle: true

ssh-pool:
  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  blockWhenExhausted: true
  #最大空闲等待时间(毫秒)，建议设置稍微长点，如90分钟
  #  maxWaitMillis: 5400000
  #最大连接数
  maxTotal: 3
  #最大空闲连接数
  maxIdle: 3
  #最小空闲连接数
  minIdle: 1
  #申请连接时 检测是否有效
  testOnBorrow: true
  #返回连接时 检测是否有效
  testOnReturn: false
  #创建连接时 检测是否有效
  testOnCreate: false
  #空闲时检测连接是否有效
  testWhileIdle: true

sftp-pool:
  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  blockWhenExhausted: true
  #最大空闲等待时间(毫秒)，建议设置稍微长点，如90分钟
  #  maxWaitMillis: 5400000
  #最大连接数
  maxTotal: 10
  #最大空闲连接数
  maxIdle: 10
  #最小空闲连接数
  minIdle: 5
  #申请连接时 检测是否有效
  testOnBorrow: true
  #返回连接时 检测是否有效
  testOnReturn: false
  #创建连接时 检测是否有效
  testOnCreate: false
  #空闲时检测连接是否有效
  testWhileIdle: false

logging:
  level:
    com.haha.gcmp: INFO
  file:
    path: ${user.home}/.gcmp/logs