server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 8388608
  devtools:
    restart:
      enabled: true  #设置开启热部署
  #      additional-paths: src/main/java #重启目录
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gcmp?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
#  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
gcmp:
  pypi-source: https://pypi.tuna.tsinghua.edu.cn/simple
  k8s-config-file-path: "src/main/resources/config"
  ftp-type: ftp
  admin-name: admin
  server-properties:
    - { host-name: node1, host-ip: 192.168.0.107, username: root, password: 123456, gpus: 1, gpu-series: GTX1080 }
  #    - { hostName: scw4000-All-Series, hostIp: 192.168.137.143, username: scw4000, password: Group416, gpus: 1, gpuSeries: GTX1080 }

  docker-client-port: 2375
  gcmp-root: /raid/gcmp
  common-data-root: /raid/gcmp/commonDataset
  docker-file-root: /raid/gcmp/dockerfiles
  data-root: /raid/gcmp/data
  temp-file-root: /raid/gcmp/temp
  task-log-root: /raid/gcmp/tasklogs
  # 每次返回到前端的任务日志大小
  task-log-limit-bytes: 1024
  # 同步k8s任务状态到数据库的间隔（s）
  task-clear-period: 10

ftp-pool:
  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  block-when-exhausted: true
  #最大空闲等待时间(毫秒)，建议设置稍微长点，如90分钟
  #  maxWaitMillis: 5400000
  #最大连接数
  max-total: 5
  #最大空闲连接数
  max-idle: 5
  #最小空闲连接数
  min-idle: 2
  #申请连接时 检测是否有效
  test-on-borrow: true
  #返回连接时 检测是否有效
  test-on-return: false
  #创建连接时 检测是否有效
  test-on-create: false
  #空闲时检测连接是否有效
  test-while-idle: true

file-ssh-pool:
  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  block-when-exhausted: true
  #最大空闲等待时间(毫秒)，建议设置稍微长点，如90分钟
  #  maxWaitMillis: 5400000
  #最大连接数
  max-total: 5
  #最大空闲连接数
  max-idle: 5
  #最小空闲连接数
  min-idle: 2
  #申请连接时 检测是否有效
  test-on-borrow: true
  #返回连接时 检测是否有效
  test-on-return: false
  #创建连接时 检测是否有效
  test-on-create: false
  #空闲时检测连接是否有效
  test-while-idle: true

status-ssh-pool:
  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  block-when-exhausted: true
  #最大空闲等待时间(毫秒)，建议设置稍微长点，如90分钟
  #  maxWaitMillis: 5400000
  #最大连接数
  max-total: 3
  #最大空闲连接数
  max-idle: 3
  #最小空闲连接数
  min-idle: 1
  #申请连接时 检测是否有效
  test-on-borrow: true
  #返回连接时 检测是否有效
  test-on-return: false
  #创建连接时 检测是否有效
  test-on-create: false
  #空闲时检测连接是否有效
  test-while-idle: true

sftp-pool:
  #连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  block-when-exhausted: true
  #最大空闲等待时间(毫秒)，建议设置稍微长点，如90分钟
  #  maxWaitMillis: 5400000
  #最大连接数
  max-total: 5
  #最大空闲连接数
  max-idle: 5
  #最小空闲连接数
  min-idle: 2
  #申请连接时 检测是否有效
  test-on-borrow: true
  #返回连接时 检测是否有效
  test-on-return: false
  #创建连接时 检测是否有效
  test-on-create: false
  #空闲时检测连接是否有效
  test-while-idle: true

logging:
  level:
    com.haha.gcmp: DEBUG
  file:
    path: ${user.home}/.gcmp/logs